name: Commit Lint

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  commitlint:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run commitlint
        run: |
            base_sha="${{ github.event.pull_request.base.sha }}"
            head_sha="${{ github.event.pull_request.head.sha }}"
            first_commit_sha=$(git rev-list --no-merges --reverse $base_sha..$head_sha | head -n 1)
            commit_message=$(git log -1 --pretty=%B $first_commit_sha)
            # we can't use npx see https://github.com/conventional-changelog/commitlint/issues/613
            echo '{}' > package.json
            npm install --no-fund --no-audit @commitlint/config-conventional @commitlint/cli
            echo "$commit_message" | ./node_modules/.bin/commitlint -g .commitlintrc

